In [2]:
import numpy as np
import torch

Create 1D, 2D, and 3D tensors using PyTorch and NumPy.

In [3]:
np_1d = np.array([1, 2, 3])
print("NumPy 1D:", np_1d)

np_2d = np.array([[1, 2],
                  [3, 4]])
print("NumPy 2D:\n", np_2d)

np_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("NumPy 3D:\n", np_3d)


NumPy 1D: [1 2 3]
NumPy 2D:
 [[1 2]
 [3 4]]
NumPy 3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
torch_1d = torch.tensor([1, 2, 3])
print("Torch 1D:", torch_1d)

torch_2d = torch.tensor([[1, 2],
                          [3, 4]])
print("Torch 2D:\n", torch_2d)

torch_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("Torch 3D:\n", torch_3d)


Torch 1D: tensor([1, 2, 3])
Torch 2D:
 tensor([[1, 2],
        [3, 4]])
Torch 3D:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


Basic Operations: Element-wise addition, subtraction, multiplication, and division.

In [5]:
np_a=np.array([1,2,3,4])
np_b=np.array([3,4,5,6])
print(np_a+ np_b)
print(np_a-np_b)
print(np_a*np_b)
print(np_a/np_b)


[ 4  6  8 10]
[-2 -2 -2 -2]
[ 3  8 15 24]
[0.33333333 0.5        0.6        0.66666667]


In [18]:
a = torch.tensor([2.0, 4.0, 6.0])
b = torch.tensor([1.0, 2.0, 3.0])

# Element-wise operations
add = a + b      # addition
sub = a - b      # subtraction
mul = a * b      # multiplication
div = a / b      # division

print("Addition:", add)
print("Subtraction:", sub)
print("Multiplication:", mul)
print("Division:", div)

Addition: tensor([3., 6., 9.])
Subtraction: tensor([1., 2., 3.])
Multiplication: tensor([ 2.,  8., 18.])
Division: tensor([2., 2., 2.])


Dot product and matrix multiplication.

In [19]:
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])

dot = torch.dot(v1, v2)
dot


tensor(32)

In [7]:
A = torch.tensor([[1, 2],
                  [3, 4]])

B = torch.tensor([[5, 6],
                  [7, 8]])

matmul = torch.matmul(A, B)
matmul


tensor([[19, 22],
        [43, 50]])

Indexing and Slicing examples (Boolean masking, extracting subtensors)

In [8]:
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print(x[0])       # First row
print(x[:, 1])    # Second column
print(x[1, 2])    # Element


tensor([10, 20, 30])
tensor([20, 50])
tensor(60)


In [9]:
y = torch.tensor([1, 2, 3, 4, 5])

mask = y > 3
print(mask)




tensor([False, False, False,  True,  True])


Use .view(), .reshape(), .unsqueeze(), and .squeeze() in PyTorch. Compare with .reshape in Numpy


In [10]:
t = torch.tensor([1, 2, 3, 4])

reshaped = t.view(2, 2)
print(reshaped)


tensor([[1, 2],
        [3, 4]])


In [11]:
reshaped = t.reshape(2, 2)
print(reshaped)


tensor([[1, 2],
        [3, 4]])


In [12]:
a = torch.tensor([1, 2, 3])

print(a.shape)

b = a.unsqueeze(0)
print(b.shape)

c = a.unsqueeze(1)
print(c.shape)


torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


In [13]:
x = torch.tensor([[1, 2, 3]])

print(x.shape)

y = x.squeeze()
print(y.shape)


torch.Size([1, 3])
torch.Size([3])


In [14]:
np_x = np.array([1, 2, 3, 4])

print(np_x.reshape(2, 2))


[[1 2]
 [3 4]]


Broadcasting- Perform operations with tensors of different shapes.


In [15]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

b = torch.tensor([10, 20, 30])

result = A + b
print(result)


tensor([[11, 22, 33],
        [14, 25, 36]])


In-place vs Out-of-place operations


In [16]:
a = torch.tensor([1, 2, 3])
a.add_(1)   # underscore = in-place

print(a)


tensor([2, 3, 4])


In [17]:

x = torch.tensor([1.0, 2.0, 3.0])
y = x + 10   # out-of-place

print("x:", x)
print("y:", y)
print("Same object?", x is y)

x: tensor([1., 2., 3.])
y: tensor([11., 12., 13.])
Same object? False
